\connect "Med_FactorUsersDB"

--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-07-22 18:06:04

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 219 (class 1259 OID 37986)
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    role character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 37985)
-- Name: roles_role_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4900 (class 0 OID 37986)
-- Dependencies: 219
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.roles (role_id, role) VALUES (1, 'ROLE_ADMIN');
INSERT INTO public.roles (role_id, role) VALUES (2, 'ROLE_RES_COMERCIAL');
INSERT INTO public.roles (role_id, role) VALUES (3, 'ROLE_RES_ACHAT');
INSERT INTO public.roles (role_id, role) VALUES (4, 'ROLE_RES_FINANCEMENT');
INSERT INTO public.roles (role_id, role) VALUES (5, 'ROLE_RES_JURIDIQUE');
INSERT INTO public.roles (role_id, role) VALUES (6, 'ROLE_VALIDATEUR');
INSERT INTO public.roles (role_id, role) VALUES (7, 'ROLE_SIGNATAIRE');
INSERT INTO public.roles (role_id, role) VALUES (8, 'ROLE_ADHERENT');


--
-- TOC entry 4906 (class 0 OID 0)
-- Dependencies: 218
-- Name: roles_role_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_role_id_seq', 1, false);


--
-- TOC entry 4753 (class 2606 OID 37990)
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);


-- Completed on 2025-07-22 18:06:05

--
-- PostgreSQL database dump complete
--

