\connect "Med_FactorContractDB"
--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-07-22 18:23:28

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5125 (class 1262 OID 50110)
-- Name: Med_FactorContractDB; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "Med_FactorContractDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'French_Tunisia.1252';


ALTER DATABASE "Med_FactorContractDB" OWNER TO postgres;

\connect "Med_FactorContractDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 272 (class 1259 OID 89027)
-- Name: statut_contrat; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.statut_contrat (
    x_statut_contrat_id_fk bigint NOT NULL,
    x_statut_contrat_code character varying(8) NOT NULL,
    x_statut_contrat_dsg character varying(64) NOT NULL,
    sys_action character varying(32) NOT NULL,
    sys_adresse_ip character varying(32) NOT NULL,
    sys_date timestamp(6) without time zone NOT NULL,
    sys_user character varying(32) NOT NULL,
    sys_user_id bigint NOT NULL
);


ALTER TABLE public.statut_contrat OWNER TO postgres;

--
-- TOC entry 271 (class 1259 OID 89026)
-- Name: statut_contrat_x_statut_contrat_id_fk_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.statut_contrat ALTER COLUMN x_statut_contrat_id_fk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.statut_contrat_x_statut_contrat_id_fk_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5119 (class 0 OID 89027)
-- Dependencies: 272
-- Data for Name: statut_contrat; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.statut_contrat (x_statut_contrat_id_fk, x_statut_contrat_code, x_statut_contrat_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (2, 'SVV', 'STATUS_VALIDATION_VALIDATION', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.716', 'admin', 1);
INSERT INTO public.statut_contrat (x_statut_contrat_id_fk, x_statut_contrat_code, x_statut_contrat_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (3, 'SVJ', 'STATUS_VALIDATION_JURIDIQUE', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.716', 'admin', 1);
INSERT INTO public.statut_contrat (x_statut_contrat_id_fk, x_statut_contrat_code, x_statut_contrat_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (4, 'SM', 'STATUS_MODIFICATION', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.716', 'admin', 1);
INSERT INTO public.statut_contrat (x_statut_contrat_id_fk, x_statut_contrat_code, x_statut_contrat_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (5, 'SV', 'STATUS_VALIDER', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.716', 'admin', 1);
INSERT INTO public.statut_contrat (x_statut_contrat_id_fk, x_statut_contrat_code, x_statut_contrat_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (6, 'SS', 'STATUS_SIGNED', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.716', 'admin', 1);
INSERT INTO public.statut_contrat (x_statut_contrat_id_fk, x_statut_contrat_code, x_statut_contrat_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (1, 'SCR', 'STATUS_CONTRAT_REDIGER', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.716', 'admin', 1);

INSERT INTO public.act_ru_filter (
    id_, rev_, resource_type_, name_, owner_, query_, properties_
) VALUES (
    '88d73dbe-fc2d-11ef-ab35-e89c254c532f',
    1,
    'Task',
    'All Tasks',
    NULL,
    '{}',
    '{"description":"Unfiltered Tasks","priority":1,"color":"#555555","refresh":false,"howUndefinedVariable":false}'
);

--
-- TOC entry 5126 (class 0 OID 0)
-- Dependencies: 271
-- Name: statut_contrat_x_statut_contrat_id_fk_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.statut_contrat_x_statut_contrat_id_fk_seq', 1, true);


--
-- TOC entry 4970 (class 2606 OID 89031)
-- Name: statut_contrat statut_contrat_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statut_contrat
    ADD CONSTRAINT statut_contrat_pkey PRIMARY KEY (x_statut_contrat_id_fk);


--
-- TOC entry 4972 (class 2606 OID 89096)
-- Name: statut_contrat uk6fxvvgw5r5mdh1owl01km9x0y; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.statut_contrat
    ADD CONSTRAINT uk6fxvvgw5r5mdh1owl01km9x0y UNIQUE (x_statut_contrat_code);


-- Completed on 2025-07-22 18:23:28

--
-- PostgreSQL database dump complete
--

