\connect "Med_FactorContractDB"
--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-07-22 18:25:26

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5125 (class 1262 OID 50110)
-- Name: Med_FactorContractDB; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "Med_FactorContractDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'French_Tunisia.1252';


ALTER DATABASE "Med_FactorContractDB" OWNER TO postgres;

\connect "Med_FactorContractDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 274 (class 1259 OID 89033)
-- Name: x_devise; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.x_devise (
    x_devise_id bigint NOT NULL,
    x_devise_code_alpha character varying(8) NOT NULL,
    x_devise_code_num character varying(8) NOT NULL,
    x_devise_dsg character varying(64) NOT NULL,
    sys_action character varying(32) NOT NULL,
    sys_adresse_ip character varying(32) NOT NULL,
    sys_date timestamp(6) without time zone NOT NULL,
    sys_user character varying(32) NOT NULL,
    sys_user_id bigint NOT NULL
);


ALTER TABLE public.x_devise OWNER TO postgres;

--
-- TOC entry 273 (class 1259 OID 89032)
-- Name: x_devise_x_devise_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.x_devise ALTER COLUMN x_devise_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.x_devise_x_devise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5119 (class 0 OID 89033)
-- Dependencies: 274
-- Data for Name: x_devise; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.x_devise (x_devise_id, x_devise_code_alpha, x_devise_code_num, x_devise_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (1, 'USD', '840', 'US Dollar', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.702', 'admin', 1);
INSERT INTO public.x_devise (x_devise_id, x_devise_code_alpha, x_devise_code_num, x_devise_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (2, 'TND', '788', 'Dinar Tunisien', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.702', 'admin', 1);
INSERT INTO public.x_devise (x_devise_id, x_devise_code_alpha, x_devise_code_num, x_devise_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (3, 'EUR', '987', 'EURO', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.702', 'admin', 1);


--
-- TOC entry 5126 (class 0 OID 0)
-- Dependencies: 273
-- Name: x_devise_x_devise_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.x_devise_x_devise_id_seq', 1, true);


--
-- TOC entry 4970 (class 2606 OID 89098)
-- Name: x_devise uk42srsp2wnovfdkqmxek4pdwu2; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.x_devise
    ADD CONSTRAINT uk42srsp2wnovfdkqmxek4pdwu2 UNIQUE (x_devise_code_num, x_devise_code_alpha);


--
-- TOC entry 4972 (class 2606 OID 89037)
-- Name: x_devise x_devise_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.x_devise
    ADD CONSTRAINT x_devise_pkey PRIMARY KEY (x_devise_id);


-- Completed on 2025-07-22 18:25:26

--
-- PostgreSQL database dump complete
--

