\connect "Med_FactorContractDB"
--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-07-22 18:27:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5125 (class 1262 OID 50110)
-- Name: Med_FactorContractDB; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "Med_FactorContractDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'French_Tunisia.1252';


ALTER DATABASE "Med_FactorContractDB" OWNER TO postgres;

\connect "Med_FactorContractDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 282 (class 1259 OID 89069)
-- Name: x_type_factoring; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.x_type_factoring (
    x_type_factoring_id bigint NOT NULL,
    x_type_factoring_bool_recours boolean NOT NULL,
    x_type_factoring_code character varying(8) NOT NULL,
    x_type_factoring_dsg character varying(64) NOT NULL,
    sys_action character varying(32) NOT NULL,
    sys_adresse_ip character varying(32) NOT NULL,
    sys_date timestamp(6) without time zone NOT NULL,
    sys_user character varying(32) NOT NULL,
    sys_user_id bigint NOT NULL
);


ALTER TABLE public.x_type_factoring OWNER TO postgres;

--
-- TOC entry 281 (class 1259 OID 89068)
-- Name: x_type_factoring_x_type_factoring_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.x_type_factoring ALTER COLUMN x_type_factoring_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.x_type_factoring_x_type_factoring_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5119 (class 0 OID 89069)
-- Dependencies: 282
-- Data for Name: x_type_factoring; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.x_type_factoring (x_type_factoring_id, x_type_factoring_bool_recours, x_type_factoring_code, x_type_factoring_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (1, true, 'TF123', 'Factoring', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.686', 'admin', 1);
INSERT INTO public.x_type_factoring (x_type_factoring_id, x_type_factoring_bool_recours, x_type_factoring_code, x_type_factoring_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (8, true, 'TF124', 'Factoring123', 'CREATE', '127.0.0.1', '2025-03-25 12:38:28.71', 'admin', 1);
INSERT INTO public.x_type_factoring (x_type_factoring_id, x_type_factoring_bool_recours, x_type_factoring_code, x_type_factoring_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (2, true, 'class', 'Factoring Classique', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.686', 'admin', 1);
INSERT INTO public.x_type_factoring (x_type_factoring_id, x_type_factoring_bool_recours, x_type_factoring_code, x_type_factoring_dsg, sys_action, sys_adresse_ip, sys_date, sys_user, sys_user_id) VALUES (3, true, 'reverser', 'Factoring Inverser', 'CREATE', '127.0.0.1', '2025-03-21 17:44:58.686', 'admin', 1);


--
-- TOC entry 5126 (class 0 OID 0)
-- Dependencies: 281
-- Name: x_type_factoring_x_type_factoring_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.x_type_factoring_x_type_factoring_id_seq', 8, true);


--
-- TOC entry 4970 (class 2606 OID 89112)
-- Name: x_type_factoring uksgbmkieq3c05c97ukrxqchkyi; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.x_type_factoring
    ADD CONSTRAINT uksgbmkieq3c05c97ukrxqchkyi UNIQUE (x_type_factoring_code);


--
-- TOC entry 4972 (class 2606 OID 89073)
-- Name: x_type_factoring x_type_factoring_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.x_type_factoring
    ADD CONSTRAINT x_type_factoring_pkey PRIMARY KEY (x_type_factoring_id);


-- Completed on 2025-07-22 18:27:43

--
-- PostgreSQL database dump complete
--

