\connect "Med_FactorContractDB"
--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-07-22 18:29:05

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 5125 (class 1262 OID 50110)
-- Name: Med_FactorContractDB; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE "Med_FactorContractDB" WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'French_Tunisia.1252';


ALTER DATABASE "Med_FactorContractDB" OWNER TO postgres;

\connect "Med_FactorContractDB"

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 298 (class 1259 OID 89492)
-- Name: y_tmm; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.y_tmm (
    y_tmm_id bigint NOT NULL,
    y_tmm_aaaa_mm character varying(255),
    sys_action character varying(32),
    sys_adresse_ip character varying(32),
    sys_date timestamp(6) without time zone NOT NULL,
    sys_user character varying(32),
    sys_user_id bigint NOT NULL,
    y_tmm_taux double precision
);


ALTER TABLE public.y_tmm OWNER TO postgres;

--
-- TOC entry 297 (class 1259 OID 89491)
-- Name: y_tmm_y_tmm_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.y_tmm ALTER COLUMN y_tmm_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.y_tmm_y_tmm_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5119 (class 0 OID 89492)
-- Dependencies: 298
-- Data for Name: y_tmm; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.y_tmm VALUES (1, '202504', 'CREATE', '127.0.0.1', '2025-04-07 12:03:43.69', 'admin', 1, 0.5);
INSERT INTO public.y_tmm VALUES (2, '202505', 'CREATE', '127.0.0.1', '2025-04-07 12:03:43.758', 'admin', 1, 0.7);


--
-- TOC entry 5126 (class 0 OID 0)
-- Dependencies: 297
-- Name: y_tmm_y_tmm_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.y_tmm_y_tmm_id_seq', 2, true);


--
-- TOC entry 4970 (class 2606 OID 89498)
-- Name: y_tmm ukr5lvlghk6qhga99pciqriglk5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.y_tmm
    ADD CONSTRAINT ukr5lvlghk6qhga99pciqriglk5 UNIQUE (y_tmm_aaaa_mm);


--
-- TOC entry 4972 (class 2606 OID 89496)
-- Name: y_tmm y_tmm_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.y_tmm
    ADD CONSTRAINT y_tmm_pkey PRIMARY KEY (y_tmm_id);


-- Completed on 2025-07-22 18:29:05

--
-- PostgreSQL database dump complete
--

